/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaMain */

#ifndef _Included_javaMain
#define _Included_javaMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaMain
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javaMain_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javaMain
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_javaMain_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     javaMain
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaMain_deinit
  (JNIEnv *, jclass);

/*
 * Class:     javaMain
 * Method:    sendTo
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_javaMain_sendTo
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     javaMain
 * Method:    recvFrom
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_javaMain_recvFrom
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
