/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaMain */

#ifndef _Included_javaMain
#define _Included_javaMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaMain
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javaMain_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
